### ISSUE TITLE
Node sizes on all parts

### ISSUE THREAD

**Issue by AccidentalDisassembly** [SpannerMonkey/KAX#1]
Most stack node sizes are incorrect. Definitions in need of a 7th variable in their definitions, e.g.:
node_stack_top = 0.0, 3.75, 0.0, 0.0, 1.0, 0.0, ***2***

**Comment by SpannerMonkey** [comment]
Hi could you please specify which parts in particular, as size 2 is not suitable for all parts  the current mk2 size parts have the same node size as stock parts .  I will enlarge the nodes on the 2 meter parts. 
cheers
