### ISSUE TITLE
IVA placeholder on cockpit

### ISSUE THREAD

**Issue by AccidentalDisassembly** [SpannerMonkey/KAX#2]
Without an IVA, it's not possible (I think?) to EVA any kerbals or see that they're in a given part. Are there any placeholder IVAs with the correct number of seats that could be used? Mk 1-2 command pod or something?

**Comment by SpannerMonkey** [comment]
The missing medium cockpit placeholder IVA has just been brought to my attention.  You can still board Kerbs in the SPH and IVA from the hatch , even though they will not show,
Next beta will include a temporary IVA until the proper one is completed.
